services:
  zookeeper:
    image: zookeeper:3.8.5
    container_name: zookeeper
    hostname: zookeeper
    networks:
      storm_network:
    volumes:
      - ./storm/config/zoo.cfg:/conf/zoo.cfg
    ports:
      - 2181:2181

  nimbus:
    image: storm:2.1.0
    container_name: nimbus
    hostname: nimbus
    command: sh -c "storm nimbus & storm ui"
    volumes:
      - ./storm/config/nimbus.yaml:/conf/storm.yaml
      - ./tagawarescheduler/target/tagawarescheduler-1.0.jar:/apache-storm-2.1.0/lib/tagawarescheduler-1.0.jar
      - ./target/Storm-IOTdata-1.0-SNAPSHOT-jar-with-dependencies.jar:/apache-storm-2.1.0/Storm-IOTdata-1.0-SNAPSHOT-jar-with-dependencies.jar
    ports:
      - 8080:8080
      - 6627:6627
    restart: always
    networks:
      storm_network:
    depends_on:
      - zookeeper

  supervisor-cloud:
    image: storm:2.1.0
    container_name: supervisor-cloud
    hostname: supervisor-cloud
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    volumes:
      - ./storm/config/supervisor.yaml:/conf/storm.yaml
    ports:
      - 6700-6703:6700-6703
    networks:
      storm_network:
    extra_hosts:
      - "mqtt-broker:192.168.1.110"
      - "supervisor-fog:192.168.1.110"

  storm-exporter:
    image: stormexporter:v1
    container_name: storm-exporter
    pull_policy: never
    environment:
      - STORM_UI_HOST=nimbus:8080
      - PORT_EXPOSE=8082
      - REFRESH_RATE=5
    networks:
      storm_network:
    ports:
      - 8082:8082
    restart: always
    depends_on:
      - nimbus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - storm-exporter
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - storm_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - storm_network

  mysql:
    image: mysql:8.4.2
    container_name: mysql
    networks:
      storm_network:
    environment:
      MYSQL_ROOT_PASSWORD: Uet123
      MYSQL_DATABASE: iotdata
      MYSQL_USER: user1
      MYSQL_PASSWORD: Uet123
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pUet123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  webapp:
    image: iot-data-api:v1
    container_name: iot-data-api
    pull_policy: never
    networks:
      storm_network:
    ports:
      - 9000:9000
    volumes:
      - ./webapp/cred.json:/opt/app/cred.json
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    extra_hosts:
      - "mqtt-broker:192.168.1.110"
      
networks:
  storm_network:
    driver: bridge

volumes:
  mysql_data:
