services:
  zookeeper:
    image: zookeeper:3.8.5
    container_name: zookeeper
    hostname: zookeeper
    networks:
      storm_network:
    volumes:
      - ./storm/config/zoo.cfg:/conf/zoo.cfg
    ports:
      - 2181:2181

  nimbus:
    image: storm:2.1.0
    container_name: nimbus
    hostname: nimbus
    command: sh -c "storm nimbus & storm ui"
    volumes:
      - ./storm/config/nimbus.yaml:/conf/storm.yaml
      - ./tagawarescheduler/target/tagawarescheduler-1.0.jar:/apache-storm-2.1.0/lib/tagawarescheduler-1.0.jar
      - ./target/Storm-IOTdata-1.0-SNAPSHOT-jar-with-dependencies.jar:/apache-storm-2.1.0/Storm-IOTdata-1.0-SNAPSHOT-jar-with-dependencies.jar
    ports:
      - 8080:8080
      - 6627:6627
    restart: always
    extra_hosts:
      - "mysql:10.0.41.102"
    networks:
      storm_network:
    depends_on:
      - zookeeper

  supervisor1:
    image: storm:2.1.0
    container_name: supervisor1
    hostname: supervisor1
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    volumes:
      - ./storm/config/supervisor.yaml:/conf/storm.yaml
    ports:
      - 6700-6703:6700-6703
    extra_hosts:
      - "mysql:10.0.41.102"
      - "supervisor2:10.0.41.102"
    networks:
      storm_network:

  mqtt-broker:
    image: mr4x2/mqtt-broker-iotdata:v1
    container_name: mqtt-broker
    networks:
      storm_network:
    ports:
      - 1883:1883

networks:
  storm_network:
    driver: bridge
