services:
  supervisor-fog:
    image: arm64v8/storm:2.5.0
    container_name: supervisor-fog
    hostname: supervisor-fog
    command: storm supervisor
    restart: always
    volumes:
      - ./storm/config/supervisor.yaml:/conf/storm.yaml
    ports:
      - 6704-6707:6704-6707
    extra_hosts:
      - "zookeeper:192.168.1.120"
      - "nimbus:192.168.1.120"
      - "mysql:192.168.1.120"
      - "supervisor-cloud:192.168.1.120"
    networks:
      storm_network:

  mqtt-broker:
    image: mqtt-broker-iotdata:v1
    container_name: mqtt-broker
    pull_policy: never
    networks:
      storm_network:
    ports:
      - 1883:1883

networks:
  storm_network:
    driver: bridge
