storm.zookeeper.servers:
  - "zookeeper"

storm.zookeeper.port: 2181

nimbus.seeds: ["nimbus"]

storm.log.dir: "/logs"

storm.local.dir: "/data"

storm.scheduler: com.edited.tagawarescheduler.TagAwareScheduler